### ISSUE TITLE
Data too long for column 'nickname' at row 1

### ISSUE THREAD

**Issue by Chillstice** [Aperture-Development/MSync-2#12]
So I have this really annoying friend, right? This is his name on steam:
`BR CHIL (ＣＡＭＰＳ LOCK mAChin BRKE)`

Here's a breakdown of the unicode: [Unicode Inspector](https://apps.timwhitlock.info/unicode/inspect?s=BR+CHIL+%28%EF%BC%A3%EF%BC%A1%EF%BC%AD%EF%BC%B0%EF%BC%B3+LOCK+mAChin+BRKE%29)

Here's the error in console:
```
[MSync] Failed to create user BR CHIL (ＣＡＭＰＳ LOCK mAChin BRKE) !
Please report this to the developer: Data too long for column 'nickname' at row 1
```

I can't really get him to change his name, and there will always be players with insane names going into the database, so I was wondering if you knew a way to patch this.

**Comment by ApertureDevelopment** [comment]
Yeah, thats a bug, but I already know how to workaround it
