### ISSUE TITLE
Lua Erroe MSync 2

### ISSUE THREAD

**Issue by Neonsy** [Aperture-Development/MSync-2#22]
Neonsy: **!msync**
[Neonsy|4|STEAM_0:1:73680268] Lua Error:

[ERROR] lua/msync/client_gui/modules/cl_mbsync.lua:1382: Calling net.Start with unpooled message name! [ http://goo.gl/qcx0y ]

Start - [C]:-1
getSettings - lua/msync/client_gui/modules/cl_mbsync.lua:1382
3. adminPanel - lua/msync/client_gui/modules/cl_mbsync.lua:720
4. InitModuleSettings - lua/msync/client_gui/cl_admin_gui.lua:231
5. InitPanel - lua/msync/client_gui/cl_admin_gui.lua:259
6. func - lua/msync/client_gui/cl_net.lua:89
7. unknown - lua/includes/extensions/net.lua:32

**MSync 2 Workshop**

**Comment by ApertureDevelopment** [comment]
Fixed in v1.0.1

Please restart your server to re-download the addon from the workshop, or download the new release from github and put it into your Addons folder.
