### ISSUE TITLE
There has been a error while loading the module querys.

### ISSUE THREAD

**Issue by Neonsy** [Aperture-Development/MSync-2#25]
[MSync] There has been a error while loading the module querys.

Please inform the Developer and send him this:

Can't connect to MySQL server on '185.234.72.59' **(111)**

**Comment by ApertureDevelopment** [comment]
Your MySQL data is invalid, please verify your MySQL data

**Comment by benwoo1110** [comment]
You provide too little info without any full error message. I also suggest reading on some troubleshooting methods:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server

**Comment by Neonsy** [comment]
I've checked it multiple times.

Everything is correct.

I even checked the IP & Port in other config files. (I have a total of 5 Addons using MySQL)


> [MSync] There has been a error while loading the module querys.

Please inform the Developer and send him this:

Can't connect to MySQL server on '185.234.72.59' (111)

That's everything the console told me.

>

**Comment by ApertureDevelopment** [comment]
That error tells you that something of your data is incorrect, try setting up the password again in the MSync menu and ``Save & Connect``

**Comment by Neonsy** [comment]
Neonsy: !msync
[Neonsy|2|STEAM_0:1:73680268] Lua Error:

[ERROR] lua/msync/client_gui/modules/cl_mrsync.lua:195: Calling net.Start with unpooled message name! [ http://goo.gl/qcx0y ]
  1. Start - [C]:-1
   2. getSettings - lua/msync/client_gui/modules/cl_mrsync.lua:195
    3. adminPanel - lua/msync/client_gui/modules/cl_mrsync.lua:132
     4. InitModuleSettings - lua/msync/client_gui/cl_admin_gui.lua:233
      5. InitPanel - lua/msync/client_gui/cl_admin_gui.lua:262
       6. func - lua/msync/client_gui/cl_net.lua:89
        7. unknown - lua/includes/extensions/net.lua:32

**Comment by ApertureDevelopment** [comment]
did you update MSync ?

**Comment by Neonsy** [comment]
Yes.

> try setting up the password again in the MSync menu and Save & Connect

I tired that as well.

**Comment by ApertureDevelopment** [comment]
Ah wait, that error happens because MSync was unable to load the modules. 

Make sure that there is no firewall in between and that your user is actually allowed to connect from the outside

**Comment by Neonsy** [comment]
If the Firewall would block my MySQL Port then none of the other Addons would connect either.

But to be sure I checked it and it's not blocked.

**Comment by Neonsy** [comment]
I'm trying something else now. I tell you the results as soon as I have some.

**Comment by Neonsy** [comment]
Ok just to be sure I re-downloaded all the addons by deleting the folders and it's still there.

I have one question: Are you sure the addon has no problems with custom ports?

**Comment by ApertureDevelopment** [comment]
Confirmed bug, bugfix is WIP

**Comment by ApertureDevelopment** [comment]
Your bug should be resolved now
