### ISSUE TITLE
Data truncated for column 'ip' at row 1

### ISSUE THREAD

**Issue by Chillstice** [Aperture-Development/MSync-2#29]
I just recently updated to the latest commit because I saw there was more development of this script.
I just replaced the /addons/msync-2 folder with the new version and didn't change any configs or touch the database hoping it would just work.

The console is logging the following:
```
[MSync] Module querys have been completed successfully
[MSync] Failed to create server !
Please report this to the developer: Data truncated for column 'ip' at row 1
```
Not exactly sure what to do about this. Should I rebuild my database? Should I change a setting or something in the config?

**Comment by ApertureDevelopment** [comment]
Yes, there has been a issue with the servers table, you should be fine by deleting only that particular table, the servers table is not used anywhere yet.

``DROP TABLE `tbl_msync_servers`;`` and then just restart your server/s. It should automatically re-create the table but this time with the correct fields

**Comment by Chillstice** [comment]
ty <3
