### ISSUE TITLE
ULX Commands are not recognized

### ISSUE THREAD

**Issue by Bryantdl7** [Aperture-Development/MSync-2#30]
Hey there, 

I am running the latest code from your github stable branch, and it is not even letting me do !msync. I have superadmin level of powers, what gives? 

In looking through your autorun I did notice that the sv_ulx.lua file is not included, is this intentional? 

My ULX is working perfectly fine, just your commands do not work either from rcon or ingame. 

Here's how I was grabbing the syntax of your commands for ULX. tried both !msync and MSync in the ingame console.
`    local OpenAdminGUI = ulx.command( "MSync", "msync.openAdminGUI", MSync.func.openAdminGUI, "!msync" )
    OpenAdminGUI:defaultAccess( ULib.ACCESS_SUPERADMIN )
    OpenAdminGUI:help( "Opens MSync Settings." )
end

--ucl.registerAccess("msync.", "superadmin", "", "MSync"	)
`

As a troubleshooting step I also pulled aWarn from my server, and gBans, as both use MYSQL, as I didnt know if your code may conflict.

**Comment by Bryantdl7** [comment]
I have also tried putting the sv_lux lua file in msync2/lua/ulx/modules/sh and directly into the autorun directory of the addon without luck. 

Additionally, i believe you may have intended line 31 to be this: 
`    local MSync = ulx.command( "MSync", "msync.openAdminGUI", MSync.func.openAdminGUI, "!msync" )
`

Not:
`    local openAdminGUI = ulx.command( "MSync", "msync.openAdminGUI", MSync.func.openAdminGUI, "!msync" )
`

**Comment by Bryantdl7** [comment]
I do not receive any errors in my RCON, indicating the code is not being executed at all: 

L 05/11/2020 - 22:57:32: "[DSTM] Bryant<2><STEAM_0:0:26745653><Team>" say "!msync"

**Comment by ApertureDevelopment** [comment]
Did you install MySQLoo? And no, that was intended.

Can you try running
``lua_openscript autorun/msync_autorun.lua`` and tell me what it replies?

**Comment by Bryantdl7** [comment]
We have MySQLoo installed for other addons already. Besides, the lack of MySQL would not inhibit a ULX command, it would instead print an error, yes?

I will provide the output in a following comment

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Bryantdl7** [comment]
The problem was me, I went quick and copied your stable branch as a zip. All is well...LOL! Noob mistake right here! 

Maybe debugging new addons at 12:30AM isn't the best choice...
