### ISSUE TITLE
Rank storage & allservers group 

### ISSUE THREAD

**Issue by Bryantdl7** [Aperture-Development/MSync-2#38]
I have all my servers set to dstm-build currently, for the sake of testing before I adjust things. 

In this state, I have two groups: 

![image](https://user-images.githubusercontent.com/5564661/81835720-93ce2f00-9510-11ea-92ef-248cc6577770.png)

I thought maybe it just made two different groups, but then I looked at my mrsync table: 
![image](https://user-images.githubusercontent.com/5564661/81835819-afd1d080-9510-11ea-86e3-57c8019fe996.png)
For the sake of consistency, I dropped myself out of the mrsync table, and the tbl_users, reconnected, and disconnected. I went back to being on the rank of owner, in group 1. 

So it appears that ranks which are set up to go to any server are in the allservers category. Is allservers to be interpreted as the overall wildcard ranks between all servers, or the group the server is in? 

Is there supposed to be two sets of groups? This might just be a documentation limitation causing this confusion, let me know.

**Comment by ApertureDevelopment** [comment]
Yes it is. The allservers group is for any data that is supposed to be the same on all servers. The possibility to change the Server_Group exists to allow server admins to seperate their servers into multible teams, while maintaining the same database. The "allservers" group exists to tell the plugin that the data is supposed to be not server_group specific, but on all servers.

A simelar system is used by a Minecraft plugin called "LuckPerms" they call it server-context
https://github.com/lucko/LuckPerms/wiki/Context#contexts-provided-by-luckperms

I am still working on writing the MSync wiki, but that explaination on their wiki should explain my intention behind the server_group

**Comment by Bryantdl7** [comment]
Got it. You might want to copy what you just said and put it in the wiki with a title as a general overview for now, that explains it enough so people understand going forward.
