### ISSUE TITLE
[MSync] Failed to create server !

### ISSUE THREAD

**Issue by Chillstice** [Aperture-Development/MSync-2#4]
I've been using this actively on 3 servers for a few weeks. 

I recently noticed issues with ulib rank syncing and found this error in the console:

`[MSync] Failed to create server !
Please report this to the developer: Data too long for column 'server_name' at row 1`

I think this might have been caused by changing the server hostname.

Should I reset the database and re-add the servers?

Is there a way to recover from this error?

**Comment by ApertureDevelopment** [comment]
Hello,

How long is your servers hostname? (characters)

**Comment by Chillstice** [comment]
hostname "Chill-Servers PropHunt 24/7|RotLock|Outfitter|Taunts|Maps"
57 char

What's the maximum length for MSync?

**Comment by ApertureDevelopment** [comment]
55 characters, i will extend that by 20 later, and add a check to crop the servername if necessary. Also I will post you a sql script later, to update the table as I found 2 mistakes in it.

**Comment by Chillstice** [comment]
:D

**Comment by ApertureDevelopment** [comment]
Run this SQL:
```sql
ALTER TABLE tbl_msync_servers
MODIFY server_group INT UNSIGNED NOT NULL, 
MODIFY server_name VARCHAR(75) NOT NULL;
```
And test this addon branch:
https://github.com/Aperture-Development/MSync-2/tree/bugfix

**Comment by ApertureDevelopment** [comment]
You could also propably just drop the servers table, as it has not much of a function currently and could be replaced easily

**Comment by ApertureDevelopment** [comment]
Assuming that this is resolved, I am closing this issue. Let me know if you have anymore troubles
