### ISSUE TITLE
Feature Request - Adding offline users to MSync 

### ISSUE THREAD

**Issue by Bryantdl7** [Aperture-Development/MSync-2#44]
**__Description:__**
Having the ability to add users to the MSync database while they are offline would improve server management productivity

**__Usage Cases:__**
This would be useful should we need to provide a user a new rank while they are offline, and have not yet played on our server. For example, we have a rank for retired staff, who have not been on in a very long time. Many of them not in a few years. Since they are not in the MSync database, we would need to currently use ulx adduserid, and add them to our users.txt file. This is not ideal, as when we provide them a new rank via ulx adduser, the users.txt always overrides it. 

**__Optional: Alternatives__**
Make a command which creates a user in MSync using just their steamid. This would allow us to manually manipulate the database, in order to set them to the appropriate rank.

**Comment by ApertureDevelopment** [comment]
I am currently implementing a system to add users to the database when they don't exist but you do actions with them. Lets say you ban SteamID `STEAM_0:0:0` but the user never joined before, now MBSync creates the user inside the database and then bans them directly

**Comment by ApertureDevelopment** [comment]
We implemented a way that will add users to their rank even if they never joined before, you just have to use `ulx adduserid` and the rank will be granted to said steamid.
