### ISSUE TITLE
Feature Request - Importing users from users.txt 

### ISSUE THREAD

**Issue by Bryantdl7** [Aperture-Development/MSync-2#45]
**__Description:__**
This is similar to our prior request, but falls more into the realm of automation. Using regex, it would be possible for you to make a command which would parse the JSON-formatted users.txt, and import said users to the MSync database. An initial command such as msync_importusers would make this process easy when people are first switching to this system. 

**__Usage Cases:__**
People moving from a longstanding reliance on the built-in ULX ranking system can have massive user files which they do not want to lose. In the current format, years of people with ranks will need to be manually tracked down by looking at the file after migration to MSync

**__Optional: Alternatives__**
Automatically parse the users.txt file on server start, and convert + delete entries after verifying they are in the database.

**Comment by ApertureDevelopment** [comment]
My intention while writing MSync was to sava data in the database from then on, if one of these users join the server and get their rank from ulx, it automatically gets added to the database when they leave. As for deleting that file it is not a good idea, I always kept in mind if a user were to remove the addon no data loss should happen, meaning that while loading from the database, MSync does not overwrite the users.txt, the storage methods of ulx run alongside with MSync and do not get overwritten by us
