### ISSUE TITLE
Bug report - allservers rank does not supersede individual server rank 

### ISSUE THREAD

**Issue by Bryantdl7** [Aperture-Development/MSync-2#46]
**__Description__**
My allservers ID is 1, my individual server is ID 2. Assume a situation where the user has an existing rank on ID 2. If they are granted an allservers rank in ID 1, Id 2 should assumedly be overridden. In its current state, it does not do this. 

**__Reproduction__**
Set a user to a non-allservers rank, then set the user to an allservers rank, and have them reconnect. The system will prioritize their per-server rank, in this case demoting them. 

I can understand having the allservers rank also rank lower, e.g. user is owner of one server and not another, but it can get confusing to track down the problem if a server, like we do, uses APromote, which quickly sets them to a specific rank before we can get them into the allservers rank.

**Comment by ApertureDevelopment** [comment]
A bugfix has been worked on and implemented. It is currently avaiable at the development branch, I exchanged the way how data is saved to the database, so when you are in a allservers rank all other ranks are removed from the user, and if you have been added to a non-allservers rank ( group specific ) you get removed from all allserver ranks ( that is to prevent that users keep their rank uppon demotion )

**Comment by ApertureDevelopment** [comment]
This bug has been fixed in the development branch and will be commited as release as soon as all tests are finished

**Comment by ApertureDevelopment** [comment]
The bug is fixed in the new release, but due to a bug in our CI-Pipeline I am unable to upload the addon to the workshop
