### ISSUE TITLE
Potential MySQLOO and libmysqlclient compatibility issue

### ISSUE THREAD

**Issue by KylerFarrar** [Aperture-Development/MSync-2#58]
**__Description__**
There seems to be an issue with the latest mysqloo and libmysqlclient versions that causes an unknown error within the addon. This also may just be my server, guidance would be appreciated.

**__Reproduction__**
mysqloo9 version: https://github.com/FredyH/MySQLOO/releases/download/9.6.1/gmsv_mysqloo_linux.dll
ibmysqlclient version: https://github.com/FredyH/MySQLOO/tree/master/MySQL/lib64/linux 

**__Error Messages__**
```
Your server is using the latest mysqloo9 version
TymuOG: !msync
[MSync] There has been a error while loading the module querys.
Please inform the Developer and send him this:
SSL connection error: unknown error number
```

This seemed to be the best way to inform you of the issue.

**Comment by ApertureDevelopment** [comment]
Hello, that error is new to me, could you please provide a few more informations?

- What database are you using?
- Which version of said database are you using
- Did you change any SSL settings for your Database?
- What OS exactly is the server running on?
- Are there any error messages prior to the one of the module queries?

**Comment by KylerFarrar** [comment]
> Hello, that error is new to me, could you please provide a few more informations?
> 
> * What database are you using?
> * Which version of said database are you using
> * Did you change any SSL settings for your Database?
> * What OS exactly is the server running on?
> * Are there any error messages prior to the one of the module queries?

There are no error messages prior to attempting to connect the database.
There have been no changes from the default installation SSL settings.
The OS is Ubuntu 20.0.4 - 64 Bit.
The Database is MySQL version 8.0.21.

I am able to connect to the database server remotely from my MacBook using MySQL Workbench, so I know it should be able to access it. The system is a VPS and the database server, garry's mod server, and addons were all installed manually by me.

**Comment by ApertureDevelopment** [comment]
So apperently this isn't a bug in MSync, but rather in MySQLoo and MySQL 8. The developer of MySQLoo is working on a solution right now, but as of now it looks like he dropped the 32bit GMod support, meaning that in the future no GMod server using the regular branch will be able to connect to MySQL.

For reference, please look here:
https://github.com/FredyH/MySQLOO/issues/60

**Comment by KylerFarrar** [comment]
> So apperently this isn't a bug in MSync, but rather in MySQLoo and MySQL 8. The developer of MySQLoo is working on a solution right now, but as of now it looks like he dropped the 32bit GMod support, meaning that in the future no GMod server using the regular branch will be able to connect to MySQL.
> 
> For reference, please look here:
> [FredyH/MySQLOO#60](https://github.com/FredyH/MySQLOO/issues/60)

Alright, I reviewed your comments and others on the issue. Someone suggested moving the server from the 32-bit main branch to x86-64 branch. Would your addon have any conflicts with me using the 64 bit DLLs and moving over to the x64 executable?

**Comment by ApertureDevelopment** [comment]
As I tested it a few hours ago, the beta branch of the MySQLoo doesn't work. Normally thought it shouldnt be a issue, you just need to remove the "64" from the dll file name

**Comment by KylerFarrar** [comment]
> As I tested it a few hours ago, the beta branch of the MySQLoo doesn't work. Normally thought it shouldnt be a issue, you just need to remove the "64" from the dll file name

Alright I decided to take the not complicated path and just use MariaDB. No issues now. Feel free to close this issue if you have no other comments.

**Comment by ApertureDevelopment** [comment]
This is a temporary solution as MariaDB is a fork of MySQL, the same issue will happen one day. Some reports are already out there of people having the same issue with MariaDB, so in the end it is either necessary to stay at a older MySQL/MariaDB server, or MySQLoo has to be updated. And as you can see from the discussion I posted above, more people are against my opinion to not drop 32bit support. So in the near future you will propably have to switch to x64

**Comment by ApertureDevelopment** [comment]
Closed because it is a error on MySQLoos side
