### ISSUE TITLE
Data too long for column 'rank' at row 1

### ISSUE THREAD

**Issue by KylerFarrar** [Aperture-Development/MSync-2#59]
**__Description__**
Attempting to use the name "communitymanager" for a rank in MSync gives you a data too long for column 'rank'.

**__Reproduction__**
Add a rank to the sync system with the name "communitymanager"

**__Error Messages__**
```
------------------------------------
[MRSync] SQL Error!
------------------------------------
Please include this in a Bug report:

Data too long for column 'rank' at row 1

------------------------------------
```

I believe this is just a varchar sizing issue, would it be possible to increase the size limit? I believe I could fix this manually myself, however, I felt it prudent to report things like this so you are aware.

**Comment by ApertureDevelopment** [comment]
With database engineering its important to keep in mind what the maximum reasonable colum lenght should be, and in this case I decided that 15 letters should be more then enough. I can increase the limit to 20, but I suggest to use shorter rank names instead.

**Comment by KylerFarrar** [comment]
> With database engineering its important to keep in mind what the maximum reasonable colum lenght should be, and in this case I decided that 15 letters should be more then enough. I can increase the limit to 20, but I suggest to use shorter rank names instead.

20 should definitely do it, but you should also probably put a catch for rank entry into MSync 2 to prevent too many characters, rather than simply having it error out in the console because some server owners will not be aware of that situation.

**Comment by ApertureDevelopment** [comment]
```ALTER TABLE `msync_dev`.`tbl_mrsync` 
CHANGE COLUMN `rank` `rank` VARCHAR(20) NOT NULL ;```

You can use that to alter your MRSync database, but I am not going to raise the limit by default. 

But for your other idea of the soft error instead of the hard one, that will be added to the MSync 1.3 milestone
